### ISSUE TITLE
Resetting Dialogue and Using END

### ISSUE THREAD

**Issue by aberizrihays** [nathanhoad/godot_dialogue_manager#121]
**Describe the bug**
In my GameState, I have a variable called Tutorial, set equal to 0.  The idea is to treat it like a simple quest, where each progression adds 1.  So one would expect that the first interaction would give the quest and add 1.  The next interaction would have a kind of running dialogue.  Then you would complete the thing, add another 1, get your completed dialogue bit, and add another 1 to advance it to the run of the mill dialogue.

~~~
~ ulisi

if tutorial = 0
	=> give_tutorial
elif tutorial = 1
	=> run_tutorial
elif tutorial = 2
	=> end_tutorial
elif tutorial = 3
	=> regular_dialogue

~ give_tutorial

Ulisi: Kiyuga, help!
set tutorial = 1
=> END

~ run_tutorial

Ulisi: You need to do something!
set tutorial = 2
=>END

~ end_tutorial

Ulisi: Thank you for helping!
Ulisi: Can I help you in some other way?
set tutorial = 3
- Yes
	=> regular_dialogue
- No
	=> END

~ regular_dialogue

Ulisi: You're a good grandson
=> END
~~~

In the Test Screen, I can't really test it because it closes out.  When I put it into my game, several things happen:
1. => END appears as its own line (in-game only, haven't had it happen in testing)
![Screenshot_1](https://user-images.githubusercontent.com/122324046/211596625-2c2abb21-10a9-473a-8e35-27e5d81e8737.png)
2. It never actually resets.  When I first tested the advancement, it went from 0 to 1, and the text changed, but then the next time I opened it up, the variable was still 1.  And it never actually advances beyond that.  Even though run_tutorial has a set, it never changes the variable, so the next time I open it up, it's still on give_tutorial.
EDIT: In the Test Screen it advances to the end but never resets.

EDIT 2: Now it's just opening to whatever random node it wants, and I haven't touched it.

Also, using Godot 3.5.1, and DM 1.17.6 because 1.17.10 broke.

**Comment by nathanhoad** [comment]
I think there are a few things going on here.

Firstly, your dialogue code has some assignments in the conditionals (I've just [pushed an update](https://github.com/nathanhoad/godot_dialogue_manager/releases/tag/v1.17.11) to show them as errors in the editor that should help it happening in the future). And the reason "=>END" shows up as dialogue is because it was missing a space between the "=>" and the "END". The dialogue should read something like this:

```
~ ulisi

if tutorial == 0
	=> give_tutorial
elif tutorial == 1
	=> run_tutorial
elif tutorial == 2
	=> end_tutorial
elif tutorial == 3
	=> regular_dialogue
=> END


~ give_tutorial

Ulisi: Kiyuga, help!
set tutorial = 1
=> END


~ run_tutorial

Ulisi: You need to do something!
set tutorial = 2
=> END


~ end_tutorial

Ulisi: Thank you for helping!
Ulisi: Can I help you in some other way?
set tutorial = 3
- Yes
	=> regular_dialogue
- No
	=> END
=> END


~ regular_dialogue

Ulisi: You're a good grandson
=> END
```

Second, when running the test scene it will start from the title nearest above the cursor position.

And lastly, the Dialogue Manager doesn't keep state itself. Each time you run it it will start with fresh state. If you want to save any values between runs you have to implement that into your game state.

(also, can you give version 1.17.11 a go and tell me if you still get errors?)

**Comment by nathanhoad** [comment]
I think there are a few things going on here.

Firstly, your dialogue code has some assignments in the conditionals (I've just [pushed an update](https://github.com/nathanhoad/godot_dialogue_manager/releases/tag/v1.17.12) to show them as errors in the editor that should help it happening in the future). And the reason "=>END" shows up as dialogue is because it was missing a space between the "=>" and the "END". The dialogue should read something like this:

```
~ ulisi

if tutorial == 0
	=> give_tutorial
elif tutorial == 1
	=> run_tutorial
elif tutorial == 2
	=> end_tutorial
elif tutorial == 3
	=> regular_dialogue
=> END


~ give_tutorial

Ulisi: Kiyuga, help!
set tutorial = 1
=> END


~ run_tutorial

Ulisi: You need to do something!
set tutorial = 2
=> END


~ end_tutorial

Ulisi: Thank you for helping!
Ulisi: Can I help you in some other way?
set tutorial = 3
- Yes
	=> regular_dialogue
- No
	=> END
=> END


~ regular_dialogue

Ulisi: You're a good grandson
=> END
```

Second, when running the test scene it will start from the title nearest above the cursor position.

And lastly, the Dialogue Manager doesn't keep state itself. Each time you run it it will start with fresh state. If you want to save any values between runs you have to implement that into your game state.

(also, can you give version 1.17.12 a go and tell me if you still get errors?)

**Comment by aberizrihays** [comment]
> Second, when running the test scene it will start from the title nearest above the cursor position.
That makes more sense now.

>(also, can you give version 1.17.12 a go and tell me if you still get errors?)
No problems in 1.17.12.
