### ISSUE TITLE
Toolbar does not appears in the new version 2.8.3

### ISSUE THREAD

**Issue by Flgado** [nathanhoad/godot_dialogue_manager#131]
**Describe the bug**
When you install the new version, 2.8.3, the toolbar does not appear. In the latest version, 2.8.1, everything works correctly.

**To Reproduce**
Install and click on the Dialogue icon
**Expected behavior**
The toolbar should appear

**Screenshots**
![image](https://user-images.githubusercontent.com/67416753/213877102-37923246-8325-4182-9524-0340107242cc.png)

**Comment by nathanhoad** [comment]
What version of Godot are you running?

**Comment by abercrowler** [comment]
I solved the problem through exchanging the first line (@icon) for the second (class name), in dialogue_resource.gd.

**Comment by EnhancedJunk** [comment]
> I solved the problem through exchanging the first line (`@icon`) for the second (class name), in dialogue_resource.gd.

@abercrowler You're probably running on a Godot version prior to Beta 13. They changed it in that beta so that `@icon` only works **before** `class_name`, not after, which is why the addon was updated to that. 
Preferably, try to always stay up to date by using the latest Godot 4 version along with the latest Dialogue Manager addon's version in order to avoid those compatibility conflicts.

**Comment by Flgado** [comment]
Hi there! Yes the problem was the version. I was using beta 10.
Thanks, very good job you have there
