### ISSUE TITLE
Translations example

### ISSUE THREAD

**Issue by stesproject** [nathanhoad/godot_dialogue_manager#141]
I read the documentation about how to handle translations, but I didn't find it really helpful.
Can you please provide an example to understand how it works?

**Comment by MarcusRiemer** [comment]
I have dug into the translation portions of the Godot Dialogue Manager quite a bit and from my perspective your question is too broad.

* Do you have any prior experience with translations in Godot? Godot Dialogue Manager very nicely re-uses the actual translation capabilities of Godot 4 itself, familiarity with that will be helpful.
* Are you using the `.csv` or the `.po` files? If you are trying to export `.po` files: The currently released version has a bug that is already fixed on `main`, see https://github.com/nathanhoad/godot_dialogue_manager/issues/142.
* Does your question involve on how to scale with many languages or dialogue files? In that case see my proposal at https://github.com/nathanhoad/godot_dialogue_manager/issues/143

Feel free to add more detail to your question, I will be happy to help :-)

**Comment by nathanhoad** [comment]
The example project (if you clone the repo instead of just downloading it you get the examples) has some translation stuff - both localised text and localised asset swaps. They all just use the builtin Godot translation handling so [the Godot docs](https://docs.godotengine.org/en/latest/tutorials/i18n/internationalizing_games.html) are a good place to start anyhow.
