### ISSUE TITLE
Dialogue plugin raises errors when launching Godot editor

### ISSUE THREAD

**Issue by MadFlyFish** [nathanhoad/godot_dialogue_manager#180]
**Describe the bug**
Every time I launch the Godot editor with the dialogue plugin enabled. It raises 2 errors.

**Affected version**
- Dialogue Manager version:  v2.15.6
- Godot version: Godot 4.0.3 rc1

**Screenshots**
![image](https://user-images.githubusercontent.com/36298330/236634533-b4f791e8-e34b-4c7e-9b1c-de54e443ba32.png)

**Comment by Selenyhr** [comment]
Sorry about the delimiter error! I've done a PR that will solve it, since I'm the one who introduced it.

As for the TLS handshake error, that seems more likely linked to the fact you're using a release candidate version (4.0.3 RC1). If it also happens with your project in 4.0.2, which is the current stable version, that would be worth looking into.

**Comment by MadFlyFish** [comment]
> ,

Thanks. The TLS error also happens in 4.0.2 stable.
