### ISSUE TITLE
Dialogue plugin raises TTS errors when launching Godot editor

### ISSUE THREAD

**Issue by MadFlyFish** [nathanhoad/godot_dialogue_manager#182]
**Describe the bug**
Every time I launch the Godot editor with the dialogue plugin enabled. It raises tts errors.

**Affected version**
- Dialogue Manager version:  v2.15.6
- Godot version: Godot 4.0.2 stable

**Screenshots**
![image](https://user-images.githubusercontent.com/36298330/236656571-2329382f-2ada-4beb-a0ce-976f7ca9d6c6.png)

**Comment by nathanhoad** [comment]
I'm not seeing this error. Can you attach a tiny project that demonstrates the issue?

**Comment by MadFlyFish** [comment]
The demo project is unloaded. Thanks for your time.
[reproduce project.zip](https://github.com/nathanhoad/godot_dialogue_manager/files/11414852/reproduce.project.zip)

**Comment by Selenyhr** [comment]
So after digging up a little, it seems that your repro project does not trigger the behaviour. Godot alerts that it couldn't save the `project.godot` file, most likely because there are missing files that it's trying to import (like `res://image/flame/flame_none.png` and other files that are within the `project.godot` file itself).

What the error code seems to mean is that your project tries to contact some HTTPS server, but it encounters error `-0x2700` (-9984 converted to hex), which for mbed-tls means that it cannot verify the validity of some SSL certificate ([source](https://techoverflow.net/2023/01/14/what-does-mbed-tls-error-code-0x2700-mean/)).

DialogueManager does indeed a https request to check for new versions at startup to https://api.github.com/repos/nathanhoad/godot_dialogue_manager/releases. Since it's Github, I'm pretty sure there is nothing wrong with their SSL certificate.

If you try disabling DialogueManager in your project, does the error message persist? If the error is indeed tied to the Github check, it would mean that there is something preventing your computer from processing TLS 1.3 connections. I would look into updating the OS :)

**Comment by MadFlyFish** [comment]
Thanks for the guide about the github side. I think I have found where the problem is.
It turns out the "FastGithub" app i installed on my pc causes the error. Disabling the app solves the problem.
Thanks!
![image](https://user-images.githubusercontent.com/36298330/236679880-f8ea65b4-7908-4964-9977-1fff31aa0ecc.png)
