### ISSUE TITLE
Add custom tags for lines

### ISSUE THREAD

**Issue by ismslv** [nathanhoad/godot_dialogue_manager#272]
**Is your feature request related to a problem? Please describe.**
There can be numerous uses for a custom tag. For example, maybe I want to style my UI element specifically, because the line is "sarcastic" or "funny" or "important". Maybe I want to distiguish different lines said by the same character. Maybe I want to "deactivate" a response because of some conditions, but not to hide it, just grey out.

**Describe the solution you'd like**
[tags] are already highlighted in the code, because they are used for translation IDs and inline conditions. Custom tags could just be parsed as a separate property and removed from the text and translation file, the same as IDs and IFs.
For example:
```gdscript
NPC: What would you response? [ID:t0f116242ca]
- This. [ID:t0f486242ca]
- That [sarcasm,important] [ID:t0f566242ca]
- Nothing [nihilism] [ID:t0f422242ca]
```

Which will give DialogueResponse with properties `text = "That"` and `tags = ["sarcasm","important"]` and POT file generation with only "That". If it's too much for [], maybe better to use {} or [[]] instead.

**Describe alternatives you've considered**
For now I just use RegEx when reading a list of responses.
```gdscript
var regex_response_tag = RegEx.new()
regex_response_tag.compile("\\s\\[(.+)\\]")

var _tagresult = regex_response_tag.search(text)
	if _tagresult:
		processTags(_tagresult.get_string(1))
		text = regex_response_tag.sub(text, "")

func processTags(tags: String):
	_tags = tags.to_lower().split(",")
	if _tags.has("important"):
		do_something()
```

**Comment by Selenyhr** [comment]
Tags are present in the syntax highlighting mostly because of BBCode within `RichTextLabel` nodes. I purposefully made it so that any BBCode-like tag is highlighted because I also use custom tags within my own game :)

However, tags cannot be removed from the POT files, because of consistency between languages that needs to be kept, for example:
```po
"Language: fr\n"

msgid "A [color=yellow]yellow[/color] submarine."
msgstr "Un sous-marin [color=yellow]jaune[/color]."
```

And the same is true for `[[]]` and `{}` blocks, since they are also used to pass data that will need to be placed at different string points in different languages.

If your intent is to use macros for characters animations and poses, or for your use case, that don't need exporting within the POT files, I've added a feature you can exploit in #243. With this option, you can use the character with preprocessed info, that you can then retranslate later after having removed your specific data:
```
NPC: What would you response? [ID:t0f116242ca]
- This. [ID:t0f486242ca]
- [sarcasm,important]: That [ID:t0f566242ca]
- [nihilism]: Nothing [ID:t0f422242ca]
```

You will need to filter your character within the balloon methods when assigning `dialogue_line`, but it solves the export problem, and makes sure the translation won't mess things up :)
Characters are passed as-is within Dialogue Manager, so you can automate quite a lot of things. I use it to modify displayed 2D sprites with attributes, as well as positions on screen for example:
```
do show_sprite("xxx")
xxx +happy at left: Glad to see you!
xxx +neutral at right: What can I help you with?
```
Since you've already managed to do it for the `dialogue_line.text`, I'm sure you can manage to achieve your wanted behavior for the character ;)

**Comment by nathanhoad** [comment]
I'm still thinking about add arbitrary tag support. In the mean time, @Selenyhr has a pretty good suggestion there 👍
