### ISSUE TITLE
Some Ideas about improving the workflow/Scalability Enhancements

### ISSUE THREAD

**Issue by RedXGames** [nathanhoad/godot_dialogue_manager#56]
I'm a huge fan of this plugin and I feel confident saying it is by far the best one available for Godot and I have few suggestions that could potentially improve the user experience and make the plugin scalable and flexible to fit any type of scenario you may come across.

**Suggestion 1 : ** Make titles shared between dialogue files (.tscn files)
Basically the ability to call titles from other dialogue files. This is helpful for couple of reasons, 
- It will keep the project more organized. 
- Remove Repetitive dialogues .
- You can make a series of events that can be called in other dialogues, In my experience, On of the strength of this plugin is not only to easily write dialogues but It's ability to call functions through dialogues makes it super helpful at making scriptable events for any scenario you may come across.  Ex : An event that changes the room the player is in with some dialogue in the middle. 

**Suggestion 2 : ** Title blocks should not stop upong meeting a new title
I can understand why blocks would end upon meeting a new title but nesting titles will make you able to save a lot of effort and time. 
So each title should end with an '=> END' if you truly want it to end
This will be explained in the Suggestion 3 example as they go together

**Suggestion 3 : **  Title blocks can execute as functions.
- You can add '()' after a title name to make it jump back to where it was called from after ending.
Just like in renpy when you call a title block, uporn reaching an END it should jump back to where it was called from, then continue the dialogue as you would normally do. it's like executing a function.
Example (This example is written with Suggestions 1 and 2 in mind): 
```
~ talk_to_mia 
=> fade_screen_in() [This could be stored in another helper file because it's repetitive]
do actor_join("mc", "left")
do actor_join("mia", "right")
=> greeting_mia()
~ mia_options 
- Video games
	=> ask_about_video_games
- Leave
mc : Okay then...I'll see you later...
=> fade_screen_out() [This could be stored in another helper file because it's repetitive]
=> END

~ greeting_mia
mc : Hi, Mia, How is your day going?
if good_mood
	mia : My day has been great so far
	mc : That's awesome
else
	mia : I was doing just fine until you showed up
	mc : Oh....
=> END

~ ask_about_video_games
mc : Is the challenge still up?
if good_mood 
	mia : Ofcourse, 50 bucks if you win
	start_playing_video_games()
	=> END
else
	mia : I don't want to play right now!
	=> mia_options
```

Anyway these are all just Suggestions based on my own experience with the plugin while using it on somewhat of a long game and most of the enhancements are inspired from renpy workflow. 
I know that they can bee too much work but maybe Nathan can consider them for the future of the plugin.

**Comment by nathanhoad** [comment]
Suggestion 1 is something I've been thinking about for version 2 (Godot 4 is going to mean a lot of changes so I'm saving the bigger stuff for when its going to be a lot of work anyhow). Once I figure out a nice way for this to work robustly I'll start prototyping something up.

Suggestion 2 is probably something I can add already (behind a compiler setting).

For Suggestion 3 I'd probably prefer a syntax like `=>< title` so that it kind of suggests returning there after it's done. Implementing this might be a little fiddly but it is probably something I can do without waiting for v2.

**Comment by nathanhoad** [comment]
I've added support for passing through titles as [a compiler setting](https://github.com/nathanhoad/godot_dialogue_manager/blob/main/docs/Settings.md#editor) and added `=><` syntax for [jumping to titles](https://github.com/nathanhoad/godot_dialogue_manager/blob/main/docs/Writing_Dialogue.md#gotos) and returning after.

I've moved suggestion 1 into issue #57 so that I can close this one.
